# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import learner_pb2 as learner__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in learner_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IngestionServiceStub(object):
    """Ingestion service: robots stream batches of transitions
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamTransitions = channel.stream_unary(
                '/distributed.IngestionService/StreamTransitions',
                request_serializer=learner__pb2.TransitionBatch.SerializeToString,
                response_deserializer=learner__pb2.Ack.FromString,
                _registered_method=True)


class IngestionServiceServicer(object):
    """Ingestion service: robots stream batches of transitions
    """

    def StreamTransitions(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IngestionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamTransitions': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamTransitions,
                    request_deserializer=learner__pb2.TransitionBatch.FromString,
                    response_serializer=learner__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distributed.IngestionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distributed.IngestionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IngestionService(object):
    """Ingestion service: robots stream batches of transitions
    """

    @staticmethod
    def StreamTransitions(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/distributed.IngestionService/StreamTransitions',
            learner__pb2.TransitionBatch.SerializeToString,
            learner__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PolicyServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetActor = channel.unary_unary(
                '/distributed.PolicyService/GetActor',
                request_serializer=learner__pb2.GetActorRequest.SerializeToString,
                response_deserializer=learner__pb2.ActorBlob.FromString,
                _registered_method=True)
        self.GetActorStream = channel.unary_stream(
                '/distributed.PolicyService/GetActorStream',
                request_serializer=learner__pb2.GetActorRequest.SerializeToString,
                response_deserializer=learner__pb2.ActorChunk.FromString,
                _registered_method=True)
        self.GetPolicyInfo = channel.unary_unary(
                '/distributed.PolicyService/GetPolicyInfo',
                request_serializer=learner__pb2.Empty.SerializeToString,
                response_deserializer=learner__pb2.PolicyInfo.FromString,
                _registered_method=True)


class PolicyServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetActor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActorStream(self, request, context):
        """Stream the actor in chunks to handle very large models
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPolicyInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PolicyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetActor': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActor,
                    request_deserializer=learner__pb2.GetActorRequest.FromString,
                    response_serializer=learner__pb2.ActorBlob.SerializeToString,
            ),
            'GetActorStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetActorStream,
                    request_deserializer=learner__pb2.GetActorRequest.FromString,
                    response_serializer=learner__pb2.ActorChunk.SerializeToString,
            ),
            'GetPolicyInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPolicyInfo,
                    request_deserializer=learner__pb2.Empty.FromString,
                    response_serializer=learner__pb2.PolicyInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distributed.PolicyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distributed.PolicyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PolicyService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetActor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed.PolicyService/GetActor',
            learner__pb2.GetActorRequest.SerializeToString,
            learner__pb2.ActorBlob.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActorStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/distributed.PolicyService/GetActorStream',
            learner__pb2.GetActorRequest.SerializeToString,
            learner__pb2.ActorChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPolicyInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed.PolicyService/GetPolicyInfo',
            learner__pb2.Empty.SerializeToString,
            learner__pb2.PolicyInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
