# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: reward_relabel.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
try:
    from google.protobuf import runtime_version as _runtime_version
except Exception:
    _runtime_version = None
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import learner_pb2 as learner__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14reward_relabel.proto\x12\x0b\x64istributed\x1a\rlearner.proto\"\xa2\x02\n\x15RelabelRewardsRequest\x12,\n\x0btransitions\x18\x01 \x03(\x0b\x32\x17.distributed.Transition\x12\x1d\n\x15language_instructions\x18\x02 \x03(\t\x12\x14\n\x0cvideo_frames\x18\x03 \x03(\x0c\x12\x17\n\x0f\x64ino_embeddings\x18\x04 \x03(\x0c\x12\x17\n\x0ftext_embeddings\x18\x05 \x03(\x0c\x12\x13\n\x0b\x65pisode_ids\x18\x06 \x03(\t\x12\x18\n\x10step_in_episodes\x18\x07 \x03(\x05\x12\x17\n\x0f\x62\x61tch_start_idx\x18\x08 \x01(\x05\x12\x15\n\rbatch_end_idx\x18\t \x01(\x05\x12\x15\n\rbatch_indices\x18\n \x03(\x05\">\n\x13ProgressPredictions\x12\x10\n\x08progress\x18\x01 \x03(\x02\x12\x15\n\rsuccess_probs\x18\x02 \x03(\x02\"\xa8\x02\n\x16RelabelRewardsResponse\x12\x0f\n\x07rewards\x18\x01 \x03(\x02\x12\x15\n\rsuccess_probs\x18\x02 \x03(\x02\x12\n\n\x02ok\x18\x03 \x01(\x08\x12\x0f\n\x07message\x18\x04 \x01(\t\x12\x66\n\x1bprogress_predictions_by_key\x18\x05 \x03(\x0b\x32\x41.distributed.RelabelRewardsResponse.ProgressPredictionsByKeyEntry\x1a\x61\n\x1dProgressPredictionsByKeyEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12/\n\x05value\x18\x02 \x01(\x0b\x32 .distributed.ProgressPredictions:\x02\x38\x01\x32\xd6\x01\n\x14RewardRelabelService\x12Y\n\x0eRelabelRewards\x12\".distributed.RelabelRewardsRequest\x1a#.distributed.RelabelRewardsResponse\x12\x63\n\x14StreamRelabelRewards\x12\".distributed.RelabelRewardsRequest\x1a#.distributed.RelabelRewardsResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reward_relabel_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RELABELREWARDSRESPONSE_PROGRESSPREDICTIONSBYKEYENTRY']._loaded_options = None
  _globals['_RELABELREWARDSRESPONSE_PROGRESSPREDICTIONSBYKEYENTRY']._serialized_options = b'8\001'
  _globals['_RELABELREWARDSREQUEST']._serialized_start=53
  _globals['_RELABELREWARDSREQUEST']._serialized_end=343
  _globals['_PROGRESSPREDICTIONS']._serialized_start=345
  _globals['_PROGRESSPREDICTIONS']._serialized_end=407
  _globals['_RELABELREWARDSRESPONSE']._serialized_start=410
  _globals['_RELABELREWARDSRESPONSE']._serialized_end=706
  _globals['_RELABELREWARDSRESPONSE_PROGRESSPREDICTIONSBYKEYENTRY']._serialized_start=609
  _globals['_RELABELREWARDSRESPONSE_PROGRESSPREDICTIONSBYKEYENTRY']._serialized_end=706
  _globals['_REWARDRELABELSERVICE']._serialized_start=709
  _globals['_REWARDRELABELSERVICE']._serialized_end=923
# @@protoc_insertion_point(module_scope)
