# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import reward_relabel_pb2 as reward__relabel__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in reward_relabel_pb2_grpc.py was generated against'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Consider upgrading your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or regenerating this code using a grpcio-tools version compatible with'
        + f' grpcio=={GRPC_VERSION}.',
        UserWarning,
    )


class RewardRelabelServiceStub(object):
    """Service for reward relabeling
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RelabelRewards = channel.unary_unary(
                '/distributed.RewardRelabelService/RelabelRewards',
                request_serializer=reward__relabel__pb2.RelabelRewardsRequest.SerializeToString,
                response_deserializer=reward__relabel__pb2.RelabelRewardsResponse.FromString,
                _registered_method=True)
        self.StreamRelabelRewards = channel.stream_stream(
                '/distributed.RewardRelabelService/StreamRelabelRewards',
                request_serializer=reward__relabel__pb2.RelabelRewardsRequest.SerializeToString,
                response_deserializer=reward__relabel__pb2.RelabelRewardsResponse.FromString,
                _registered_method=True)


class RewardRelabelServiceServicer(object):
    """Service for reward relabeling
    """

    def RelabelRewards(self, request, context):
        """Relabel rewards for a batch of transitions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamRelabelRewards(self, request_iterator, context):
        """Stream-based relabeling for better throughput
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RewardRelabelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RelabelRewards': grpc.unary_unary_rpc_method_handler(
                    servicer.RelabelRewards,
                    request_deserializer=reward__relabel__pb2.RelabelRewardsRequest.FromString,
                    response_serializer=reward__relabel__pb2.RelabelRewardsResponse.SerializeToString,
            ),
            'StreamRelabelRewards': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamRelabelRewards,
                    request_deserializer=reward__relabel__pb2.RelabelRewardsRequest.FromString,
                    response_serializer=reward__relabel__pb2.RelabelRewardsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distributed.RewardRelabelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distributed.RewardRelabelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RewardRelabelService(object):
    """Service for reward relabeling
    """

    @staticmethod
    def RelabelRewards(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed.RewardRelabelService/RelabelRewards',
            reward__relabel__pb2.RelabelRewardsRequest.SerializeToString,
            reward__relabel__pb2.RelabelRewardsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamRelabelRewards(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/distributed.RewardRelabelService/StreamRelabelRewards',
            reward__relabel__pb2.RelabelRewardsRequest.SerializeToString,
            reward__relabel__pb2.RelabelRewardsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
