import numpy as np


TASK_TO_LANG = {
    "button-press-v3": "Press the button from side",
    "button-press-topdown-wall-v3": "Press the button from top",
    "coffee-pull-v3": "Pull the coffee cup",
    "dial-turn-v3": "Turn the dial",
    "door-open-v3": "Open the door",
    "door-unlock-v3": "Turn door lock clockwise",
    "drawer-close-v3": "Close the drawer",
    "drawer-open-v3": "Open the drawer",
    "faucet-open-v3": "Open the faucet",
    "handle-press-v3": "Press the handle",
    "handle-pull-side-v3": "Pull the handle up from the side",
    "peg-insert-side-v3": "Insert the peg from the side",
    "pick-place-v3": "Pick up the block and placing it to the goal position",
    "plate-slide-v3": "Slide the plate into the gate",
    "plate-slide-back-side-v3": "Slide the plate out of the gate from the side",
    "push-v3": "Push the block to the goal",
    "reach-v3": "Reach the goal",
    "stick-push-v3": "Push the stick",
    "stick-pull-v3": "Pull the stick",
    "window-open-v3": "Open the window",
    "hand-insert-v3": "Pick up the block and insert it into the hole",
    "button-press-wall-v3": "Press the button from side",
    # "button-press-topdown-v3": "Press the button from top",
    # "coffee-push-v3": "Push the coffee cup",
    "coffee-button-v3": "Press the coffee button",
    # "door-close-v3": "Close the door",
    "door-lock-v3": "Turn door lock counter-clockwise",
    "faucet-close-v3": "Close the faucet",
    "handle-press-side-v3": "Press the handle from side",
    # "handle-pull-v3": "Pull the handle",
    # "pick-place-wall-v3": "Pick up the block and place it to the goal position",
    # "plate-slide-back-v3": "Slide the plate out of the gate",
    # "plate-slide-side-v3": "Slide the plate into the gate from the side",
    # "push-back-v3": "Push the block back to the goal",
    "reach-wall-v3": "Reach the goal",
    # "soccer-v3": "Slide the ball into the gate",
    "window-close-v3": "Close the window",
    "sweep-into-v3": "Sweep the block into the hole",
}
