# Basic IQL parameters
batch_size: 256
tau: 0.005
gamma: 0.99
target_update_interval: 1

# IQL-specific parameters
advantage_temp: 3  # Temperature for advantage weighting
expectile: 0.7  # Expectile for value function regression
clip_score: 100.0  # Clipping term on the advantage temp
policy_extraction: "awr"  # ["awr", "ddpg"] policy extraction algorithm
ddpg_bc_weight: 0.1  # DDPG's behavior cloning weight (when policy_extraction="ddpg")

# Training configuration
num_critics: 5 # Number of critics in the ensemble
n_critics_to_sample: 2  # Number of critics to sample from
num_updates_per_train_step: 1
pooled_critic_features: true

# Optimizer configurations
actor_optimizer_lr: 3e-4
actor_optimizer_eps: 1.0e-8
actor_optimizer_weight_decay: 0.0

critic_optimizer_lr: 3e-4
critic_optimizer_betas: [0.9, 0.999]
critic_optimizer_eps: 1.0e-8
critic_optimizer_weight_decay: 0.0

v_net_optimizer_lr: 3e-4
v_net_optimizer_betas: [0.9, 0.999]
v_net_optimizer_eps: 1.0e-8
v_net_optimizer_weight_decay: 0.0

